version: '3.8'

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: balance-api-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - balance-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balance-api
    restart: always
    depends_on:
      - postgres
    environment:
      - PORT=${API_PORT}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - balance-network

networks:
  balance-network:
    driver: bridge

volumes:
  postgres_data:
